### ISSUE TITLE
got errors when trying to run hoyolab.py

### ISSUE THREAD

**Issue by seriaati** [c3kay/hoyolab-rss-feeds#3]
```
PS C:\Users\seria\Downloads\hoyolab-rss-feeds-1.4.2\hoyolab-rss-feeds-1.4.2> python .\hoyolab.py
Traceback (most recent call last):
  File "C:\Users\seria\Downloads\hoyolab-rss-feeds-1.4.2\hoyolab-rss-feeds-1.4.2\hoyolab.py", line 389, in <module>
    asyncio.run(create_game_feeds_from_config())
  File "C:\Users\seria\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\seria\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\seria\Downloads\hoyolab-rss-feeds-1.4.2\hoyolab-rss-feeds-1.4.2\hoyolab.py", line 368, in create_game_feeds_from_config
    await asyncio.gather(
  File "C:\Users\seria\Downloads\hoyolab-rss-feeds-1.4.2\hoyolab-rss-feeds-1.4.2\hoyolab.py", line 297, in create_game_feeds
    feed_items_by_category = await load_json_feed_items(json_path)
  File "C:\Users\seria\Downloads\hoyolab-rss-feeds-1.4.2\hoyolab-rss-feeds-1.4.2\hoyolab.py", line 147, in load_json_feed_items
    feed = json.loads(feed_json)
  File "C:\Users\seria\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\seria\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\seria\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by c3kay** [comment]
It would be helpful, if you could also post your config file and the JSON feed file (if exists), since the feed file could not be decoded.
